username: ninajovic  # your UF HPC username
mp_api: BXc3Ghdzk6tFpa1T  # your Materials Project API key
normal_binary: /home/mashton/vasp.5.4.1/bin/vasp # /path/to/std/vasp/executable
twod_binary: /home/mashton/vasp.5.4.1/bin/vasp_noz  # /path/to/2D/vasp/executable
vdw_kernel: /ufrc/hennig/ninajovic/   # /path/to/vdw_kernel.bindat  (leave as null if the kernel is hard-coded into VASP)
potentials: /home/ninajovic/POTCAR/POT_GGA_PAW_PBE/  # /path/to/POTCAR/files
queue_system: slurm  # Change to pbs if on a PBS system
queue_template: config_files/ #path/to/queue/template containing account info, processor config 'submit_script'
